name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }} for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross: false
          
          # Linux ARMv7
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            cross: true
          
          # Linux AArch64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cross: true
          
          # macOS AArch64
          - os: macos-latest
            target: aarch64-apple-darwin
            cross: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
    
    - name: Install cross (for cross-compilation)
      if: matrix.cross
      run: cargo install cross
    
    - name: Build with cargo
      if: ${{ !matrix.cross }}
      run: cargo build --verbose --target ${{ matrix.target }}
    
    - name: Build with cross
      if: matrix.cross
      run: cross build --verbose --target ${{ matrix.target }}
    
    - name: Run tests with cargo
      if: ${{ !matrix.cross }}
      run: cargo test --verbose --target ${{ matrix.target }}
    
    - name: Run tests with cross
      if: matrix.cross
      run: cross test --verbose --target ${{ matrix.target }}
